import Foundation
import PopplerUtils
import Testing

@testable import PopplerKit

// ─────────────────────────────────────────────────────────────────────────────
// MARK: - Invoice PDF facts (from pdfinfo / pdfimages)
//
//   Producer:  Prince 16 (www.princexml.com)
//   Pages:     1
//   Page size: 595.276 × 841.89 pts  (ISO A4)
//   PDF:       1.5   Encrypted: no   Form: none   JS: no
//
//   Embedded images  (pdfimages -list):
//     obj 17  80 × 78 px   ICC colour   96 DPI   ~559 B   ← YesLogic logo
//     obj 17  80 × 78 px   grayscale             ~29 B    ← alpha mask (smask)
// ─────────────────────────────────────────────────────────────────────────────

// MARK: - PopplerKit: text extraction, structure, rendering

/// Tests the YesLogic invoice PDF using PopplerKit's in-process C++ binding.
///
/// The invoice was generated by Prince 16 (a CSS → PDF renderer) and contains:
/// - Standard invoice fields: company, address, date, amount, banking details
/// - A YesLogic logo stored as an 80 × 78 px ICC-colour image with an alpha mask
@Suite("Invoice — PopplerKit (text, structure, rendering)")
struct InvoicePopplerKitTests {

    let doc: PopplerDocument

    init() throws {
        doc = try PopplerDocument.load(from: invoicePDF())
    }

    // MARK: Structure

    @Test("Single-page A4 invoice")
    func pageCount() {
        #expect(doc.pageCount == 1)
    }

    @Test("Page dimensions match ISO A4 (595 × 842 pt)")
    func pageDimensions() throws {
        let page = try doc.page(at: 0)
        // A4: 595.276 × 841.890 pts — allow ±1 pt for floating-point rounding
        #expect(page.cropBox.width > 594 && page.cropBox.width < 597)
        #expect(page.cropBox.height > 840 && page.cropBox.height < 843)
    }

    @Test("Produced by Prince 16 (CSS → PDF renderer)")
    func producer() {
        // doc.producer is populated from the PDF info dictionary
        let producer = doc.producer ?? ""
        #expect(producer.contains("Prince"), "Expected 'Prince' in producer, got: '\(producer)'")
    }

    @Test("PDF version 1.5")
    func pdfVersion() {
        let v = doc.pdfVersion
        #expect(v.major == 1)
        #expect(v.minor == 5)
    }

    @Test("Not encrypted and all permissions granted")
    func securityAndPermissions() {
        #expect(!doc.isEncrypted)
        #expect(!doc.isLocked)
        #expect(doc.formType == .none)
        #expect(!doc.hasJavaScript)
        let p = doc.permissions
        #expect(p.contains(.print))
        #expect(p.contains(.copy))
        #expect(p.contains(.accessibility))
    }

    // MARK: Text extraction — known invoice fields

    @Test("Full text contains company identity")
    func companyIdentity() async throws {
        let text = try await doc.extractText()
        #expect(text.contains("YesLogic"))
        #expect(text.contains("Bouverie"))  // street address
        #expect(text.contains("Carlton"))  // suburb
        #expect(text.contains("ABN"))  // Australian Business Number
        #expect(text.contains("32 101 193 560"))  // ABN value
    }

    @Test("Full text contains invoice header fields")
    func invoiceHeader() async throws {
        let text = try await doc.extractText()
        #expect(text.contains("161126"))  // invoice number
        #expect(text.contains("Nov 26, 2016"))  // invoice date
        #expect(text.contains("30 days"))  // payment terms
    }

    @Test("Full text contains line-item and total")
    func lineItem() async throws {
        let text = try await doc.extractText()
        #expect(text.contains("Prince"))  // product name
        #expect(text.contains("950.00"))  // USD amount
        #expect(text.contains("USD"))  // currency
    }

    @Test("Full text contains all banking details")
    func bankingDetails() async throws {
        let text = try await doc.extractText()
        #expect(text.contains("Commonwealth Bank"))
        #expect(text.contains("CTBAAU2S"))  // SWIFT/BIC code — highly specific
        #expect(text.contains("13201652"))  // account number
        #expect(text.contains("063010") || text.contains("063019"))  // BSB number
    }

    // MARK: Per-page and layout options

    @Test("Physical layout preserves tabular invoice structure")
    func physicalLayoutTable() async throws {
        let text = try await doc.extractText(layout: .physical)
        // Physical mode must still include key fields
        #expect(text.contains("161126"))
        #expect(text.contains("950.00"))
        #expect(text.contains("CTBAAU2S"))
    }

    // MARK: Search

    @Test("search() locates the SWIFT code exactly")
    func searchSwiftCode() throws {
        let page = try doc.page(at: 0)
        let hits = page.search(for: "CTBAAU2S")
        #expect(!hits.isEmpty, "CTBAAU2S must be found in the invoice")
        #expect(hits.allSatisfy { $0.width > 0 && $0.height > 0 })
    }

    @Test("search() locates the invoice number")
    func searchInvoiceNumber() throws {
        let page = try doc.page(at: 0)
        let hits = page.search(for: "161126")
        #expect(!hits.isEmpty)
    }

    @Test("SWIFT code hit rect feeds into text(in:) for context extraction")
    func searchRectToRegion() throws {
        let page = try doc.page(at: 0)
        guard let hit = page.search(for: "CTBAAU2S").first else {
            Issue.record("CTBAAU2S not found")
            return
        }
        // The invoice uses a two-column layout: label ("Bank SWIFT code:") is ~250 pt
        // to the left; "CTBAAU2S" is in the right value column.  Expanding the hit
        // rect by a few points gives a snippet that reliably contains the value.
        let region = PopplerRect(
            left: hit.left - 5,
            top: hit.top - 4,
            right: hit.right + 5,
            bottom: hit.bottom + 4
        )
        let context = page.text(in: region)
        // The extracted snippet must contain the searched value
        #expect(context.contains("CTBAAU2S"))
        // And it must not be unreasonably long (confirming we got a tight region)
        #expect(context.count < 50)
    }

    // MARK: TextBoxes

    @Test("textBoxes() returns coordinate-accurate word boxes")
    func textBoxCoordinates() throws {
        let page = try doc.page(at: 0)
        let boxes = page.textBoxes()
        #expect(!boxes.isEmpty)

        for box in boxes {
            #expect(box.boundingBox.left >= -1)
            #expect(box.boundingBox.top >= -1)
            #expect(box.boundingBox.right <= page.cropBox.width + 5)
            #expect(box.boundingBox.bottom <= page.cropBox.height + 5)
            #expect(box.boundingBox.width > 0)
            #expect(box.boundingBox.height > 0)
        }
    }

    // MARK: Rendering — confirms logo pixels are present

    @Test("Page renders to an A4-proportioned PNG")
    func renderingProducesA4Image() throws {
        let renderer = PopplerRenderer()
        renderer.setAntialiasing(true)
        let page = try doc.page(at: 0)
        guard let image = renderer.render(page: page, xres: 72, yres: 72) else {
            Issue.record("render() returned nil")
            return
        }
        // A4 at 72 DPI ≈ 595 × 842 px; allow ±10 px
        #expect(image.width > 580 && image.width < 615)
        #expect(image.height > 828 && image.height < 858)
        #expect(!image.data.isEmpty)
    }

    @Test("renderToData() produces non-empty PNG for the invoice page")
    func renderToDataInvoice() throws {
        let renderer = PopplerRenderer()
        let page = try doc.page(at: 0)
        let data = renderer.renderToData(page: page, xres: 96, format: .png)
        #expect(data != nil)
        // PNG at 96 DPI for an A4 page with text and an image should be several KB
        #expect((data?.count ?? 0) > 5_000)
    }
}

// MARK: - PopplerUtils: embedded image extraction

/// Tests that `PopplerUtils.extractEmbeddedImages` correctly extracts the YesLogic logo.
///
/// `pdfimages -list` on the invoice reports exactly one image object (obj 17, 80 × 78 px,
/// ICC colour, 96 DPI) plus its alpha mask (smask).  With `-png` both are saved as
/// separate PNG files, so we expect 1–2 extracted files.
@Suite("Invoice — PopplerUtils (embedded image extraction)")
struct InvoiceImageTests {

    let pdfURL: URL

    init() throws {
        pdfURL = try invoicePDF()
    }

    @Test("extractEmbeddedImages() finds the YesLogic logo")
    func extractsLogo() async throws {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("invoice_images_\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: tmp) }

        let files = try await PopplerUtils.extractEmbeddedImages(
            from: pdfURL,
            into: tmp,
            format: .png
        )

        // pdfimages reports 1 colour image + 1 smask → 1 or 2 PNG files
        #expect(!files.isEmpty, "Expected at least one extracted image (the logo)")
        #expect(files.count <= 3, "Unexpectedly many images extracted: \(files.count)")

        // Every extracted file must be non-empty
        for file in files {
            let size = (try? file.resourceValues(forKeys: [.fileSizeKey]))?.fileSize ?? 0
            #expect(size > 0, "\(file.lastPathComponent) is empty")
        }
    }

    @Test("Extracted logo files are PNG format")
    func extractedFilesArePNG() async throws {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("invoice_png_\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: tmp) }

        let files = try await PopplerUtils.extractEmbeddedImages(
            from: pdfURL,
            into: tmp,
            format: .png
        )

        guard !files.isEmpty else {
            Issue.record("No images extracted")
            return
        }
        let extensions = Set(files.map { $0.pathExtension.lowercased() })
        // PNG extraction should produce .png files (alpha mask may also be .png)
        #expect(
            extensions.isSubset(of: ["png", "ppm", "pbm"]),
            "Unexpected file extensions: \(extensions)")
    }

    @Test("Logo image is small (fits 80 × 78 px source — ~30–5000 bytes after compression)")
    func logoFileSize() async throws {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("invoice_size_\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: tmp) }

        let files = try await PopplerUtils.extractEmbeddedImages(
            from: pdfURL,
            into: tmp,
            format: .png
        )

        // The primary colour image (559 B compressed in the PDF) should decode to a
        // small PNG.  The smask is even smaller.  Neither should exceed ~50 KB for
        // an 80 × 78 px source image.
        for file in files {
            let bytes = try Data(contentsOf: file).count
            #expect(bytes > 0, "\(file.lastPathComponent) is empty")
            #expect(bytes < 50_000, "\(file.lastPathComponent) is suspiciously large: \(bytes) B")
        }
    }

}
